
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jul 29 00:05:14 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 23;
  public static final int READ = 4;
  public static final int IDENT = 30;
  public static final int SEMICOLON = 10;
  public static final int RBRACE = 18;
  public static final int RPARENT = 16;
  public static final int CHAR = 28;
  public static final int RETURN = 9;
  public static final int LBRACE = 17;
  public static final int LBRACKET = 13;
  public static final int RBRACKET = 14;
  public static final int PROGRAM = 2;
  public static final int NUM = 27;
  public static final int SUB = 25;
  public static final int INC = 19;
  public static final int LPARENT = 15;
  public static final int COMMA = 11;
  public static final int EOF = 0;
  public static final int DIV = 22;
  public static final int ADD = 24;
  public static final int DEC = 20;
  public static final int CONST = 6;
  public static final int PRINT = 3;
  public static final int error = 1;
  public static final int DOT = 12;
  public static final int ENUM = 7;
  public static final int ASSIGN = 26;
  public static final int NEW = 5;
  public static final int BOOL = 29;
  public static final int MUL = 21;
  public static final int VOID = 8;
}

