/* The following code was generated by JFlex 1.4.3 on 7/24/19 2:40 PM */

package rs.ac.bg.etf.pp1;

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 7/24/19 2:40 PM from the specification file
 * <tt>spec/mjlexer.flex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\1\2\1\2\1\4\1\0\1\2\1\3\22\0\1\1\4\46"+
    "\1\42\1\46\1\45\1\32\1\33\1\40\1\36\1\26\1\37\1\27"+
    "\1\41\12\44\1\46\1\25\1\46\1\43\3\46\32\51\1\30\1\46"+
    "\1\31\1\46\1\52\1\46\1\11\1\51\1\21\1\20\1\16\1\47"+
    "\1\10\1\51\1\13\2\51\1\50\1\12\1\14\1\7\1\5\1\51"+
    "\1\6\1\22\1\15\1\23\1\24\1\17\3\51\1\34\1\52\1\35"+
    "\1\46\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\1\10\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\1\1\3\2\24"+
    "\7\3\1\25\1\26\1\0\1\3\1\27\4\3\1\30"+
    "\4\3\1\31\3\3\1\32\1\3\1\33\1\34\1\3"+
    "\1\35\1\3\1\36\1\3\1\37\1\3\1\40\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\126\0\201\0\254\0\327\0\u0102"+
    "\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9\0\126\0\126\0\126"+
    "\0\126\0\126\0\126\0\126\0\126\0\126\0\u0204\0\u022f"+
    "\0\126\0\u025a\0\126\0\126\0\u0285\0\u02b0\0\u02db\0\126"+
    "\0\u0306\0\u0331\0\u035c\0\u0387\0\u03b2\0\u03dd\0\u0408\0\u0433"+
    "\0\126\0\126\0\u045e\0\u0489\0\126\0\u04b4\0\u04df\0\u050a"+
    "\0\u0535\0\u0102\0\u0560\0\u058b\0\u05b6\0\u05e1\0\126\0\u060c"+
    "\0\u0637\0\u0662\0\u0102\0\u068d\0\u0102\0\u0102\0\u06b8\0\u0102"+
    "\0\u06e3\0\u0102\0\u070e\0\u0102\0\u0739\0\u0102\0\u0102";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\0\1\6\1\7\5\10\1\11"+
    "\1\12\1\13\2\10\1\14\2\10\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\3"+
    "\1\37\2\10\1\3\3\40\1\41\1\0\46\40\57\0"+
    "\1\4\53\0\1\10\1\42\16\10\17\0\1\10\2\0"+
    "\4\10\5\0\11\10\1\43\6\10\17\0\1\10\2\0"+
    "\4\10\5\0\20\10\17\0\1\10\2\0\4\10\5\0"+
    "\11\10\1\44\6\10\17\0\1\10\2\0\4\10\5\0"+
    "\1\10\1\45\16\10\17\0\1\10\2\0\4\10\5\0"+
    "\7\10\1\46\10\10\17\0\1\10\2\0\4\10\5\0"+
    "\2\10\1\47\15\10\17\0\1\10\2\0\4\10\5\0"+
    "\2\10\1\50\15\10\17\0\1\10\2\0\4\10\36\0"+
    "\1\51\53\0\1\52\54\0\1\40\55\0\1\35\7\0"+
    "\1\53\3\0\46\53\5\0\4\10\1\54\13\10\17\0"+
    "\1\10\2\0\4\10\4\0\1\55\53\0\2\10\1\56"+
    "\3\10\1\57\11\10\17\0\1\10\2\0\4\10\5\0"+
    "\4\10\1\60\3\10\1\61\7\10\17\0\1\10\2\0"+
    "\4\10\5\0\12\10\1\62\5\10\17\0\1\10\2\0"+
    "\4\10\5\0\16\10\1\63\1\10\17\0\1\10\2\0"+
    "\4\10\5\0\16\10\1\64\1\10\17\0\1\10\2\0"+
    "\4\10\5\0\7\10\1\65\10\10\17\0\1\10\2\0"+
    "\4\10\5\0\6\10\1\66\11\10\17\0\1\10\2\0"+
    "\4\10\45\0\1\67\12\0\20\10\17\0\1\10\2\0"+
    "\1\10\1\70\2\10\5\0\3\10\1\71\14\10\17\0"+
    "\1\10\2\0\4\10\5\0\7\10\1\72\10\10\17\0"+
    "\1\10\2\0\4\10\5\0\13\10\1\73\4\10\17\0"+
    "\1\10\2\0\4\10\5\0\16\10\1\74\1\10\17\0"+
    "\1\10\2\0\4\10\5\0\11\10\1\75\6\10\17\0"+
    "\1\10\2\0\4\10\5\0\5\10\1\76\12\10\17\0"+
    "\1\10\2\0\4\10\5\0\15\10\1\77\2\10\17\0"+
    "\1\10\2\0\4\10\5\0\13\10\1\100\4\10\17\0"+
    "\1\10\2\0\4\10\5\0\15\10\1\63\2\10\17\0"+
    "\1\10\2\0\4\10\5\0\1\10\1\101\16\10\17\0"+
    "\1\10\2\0\4\10\5\0\10\10\1\102\7\10\17\0"+
    "\1\10\2\0\4\10\5\0\1\10\1\103\16\10\17\0"+
    "\1\10\2\0\4\10\5\0\10\10\1\104\7\10\17\0"+
    "\1\10\2\0\4\10\5\0\4\10\1\105\13\10\17\0"+
    "\1\10\2\0\4\10\5\0\7\10\1\106\10\10\17\0"+
    "\1\10\2\0\4\10\5\0\5\10\1\107\12\10\17\0"+
    "\1\10\2\0\4\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1892];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\11\1\11\11\2\1\1\11\1\1\2\11"+
    "\3\1\1\11\10\1\2\11\1\0\1\1\1\11\11\1"+
    "\1\11\20\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

	private Symbol new_symbol(int type) {
		return new Symbol(type, yyline+1, yycolumn);
	}
	
	private Symbol new_symbol(int type, Object value) {
		return new Symbol(type, yyline+1, yycolumn, value);
	}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 33: 
          { return new_symbol(sym.PROGRAM, yytext());
          }
        case 34: break;
        case 26: 
          { return new_symbol(sym.READ, yytext());
          }
        case 35: break;
        case 24: 
          { return new_symbol(sym.NEW, yytext());
          }
        case 36: break;
        case 15: 
          { return new_symbol(sym.MUL, yytext());
          }
        case 37: break;
        case 10: 
          { return new_symbol(sym.RPARENT, yytext());
          }
        case 38: break;
        case 4: 
          { return new_symbol(sym.SEMICOLON, yytext());
          }
        case 39: break;
        case 5: 
          { return new_symbol(sym.COMMA, yytext());
          }
        case 40: break;
        case 27: 
          { return new_symbol(sym.BOOL, new Boolean(yytext()));
          }
        case 41: break;
        case 28: 
          { return new_symbol(sym.ENUM, yytext());
          }
        case 42: break;
        case 25: 
          { return new_symbol(sym.CHAR, new Character(yytext().charAt(1)));
          }
        case 43: break;
        case 23: 
          { yybegin(YYINITIAL);
          }
        case 44: break;
        case 1: 
          { System.err.println("Leksicka greska ("+yytext()+") u liniji "+(yyline+1));
          }
        case 45: break;
        case 9: 
          { return new_symbol(sym.LPARENT, yytext());
          }
        case 46: break;
        case 20: 
          { yybegin(COMMENT);
          }
        case 47: break;
        case 19: 
          { return new_symbol(sym.NUM, new Integer(yytext()));
          }
        case 48: break;
        case 12: 
          { return new_symbol(sym.RBRACE, yytext());
          }
        case 49: break;
        case 16: 
          { return new_symbol(sym.DIV, yytext());
          }
        case 50: break;
        case 11: 
          { return new_symbol(sym.LBRACE, yytext());
          }
        case 51: break;
        case 18: 
          { return new_symbol(sym.ASSIGN, yytext());
          }
        case 52: break;
        case 6: 
          { return new_symbol(sym.DOT, yytext());
          }
        case 53: break;
        case 7: 
          { return new_symbol(sym.LBRACKET, yytext());
          }
        case 54: break;
        case 31: 
          { return new_symbol(sym.CONST, yytext());
          }
        case 55: break;
        case 32: 
          { return new_symbol(sym.RETURN, yytext());
          }
        case 56: break;
        case 14: 
          { return new_symbol(sym.SUB, yytext());
          }
        case 57: break;
        case 17: 
          { return new_symbol(sym.MOD, yytext());
          }
        case 58: break;
        case 8: 
          { return new_symbol(sym.RBRACKET, yytext());
          }
        case 59: break;
        case 21: 
          { return new_symbol(sym.INC, yytext());
          }
        case 60: break;
        case 30: 
          { return new_symbol(sym.PRINT, yytext());
          }
        case 61: break;
        case 29: 
          { return new_symbol(sym.VOID, yytext());
          }
        case 62: break;
        case 3: 
          { return new_symbol(sym.IDENT, yytext());
          }
        case 63: break;
        case 22: 
          { return new_symbol(sym.DEC, yytext());
          }
        case 64: break;
        case 2: 
          { 
          }
        case 65: break;
        case 13: 
          { return new_symbol(sym.ADD, yytext());
          }
        case 66: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	return new_symbol(sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
